ServerEvents.tags('entity_type', (event) => {
    event
        .get('enigmatica:mob_spawner_blacklist')
        .add([
            /occultism/,
            /ars_nouveau:familiar_.*/,
            /ars_elemental:.*_familiar/,
            'twilightforest:naga',
            'twilightforest:lich',
            'twilightforest:minoshroom',
            'twilightforest:hydra',
            'twilightforest:knight_phantom',
            'twilightforest:ur_ghast',
            'twilightforest:alpha_yeti',
            'twilightforest:snow_queen',
            'twilightforest:quest_ram',
            'minecraft:wither',
            'minecraft:ender_dragon',
            'quark:stoneling'
        ]);
});
