//priority: 1000

const cobbleworks = {
    basalts: ['minecraft:basalt', 'quark:myalite', 'quark:dusky_myalite', 'minecraft:end_stone'],
    cobblestones: [
        'byg:cobbled_ether_stone',
        'byg:dacite_cobblestone',
        'byg:purpur_stone',
        'byg:red_rock',
        'byg:scoria_cobblestone',
        'byg:soapstone',
        'byg:travertine',
        'minecraft:cobbled_deepslate'
    ],
    stones: [
        'byg:black_sandstone',
        'byg:blue_sandstone',
        'byg:brimstone',
        'byg:cryptic_stone',
        'byg:dacite',
        'byg:ether_stone',
        'byg:pink_sandstone',
        'byg:purple_sandstone',
        'byg:scoria_stone',
        'byg:white_sandstone',
        'byg:windswept_sandstone',
        'create:asurine',
        'create:crimsite',
        'create:limestone',
        'create:ochrum',
        'create:scorchia',
        'create:scoria',
        'create:veridium',
        'minecraft:andesite',
        'minecraft:deepslate',
        'minecraft:diorite',
        'minecraft:dripstone_block',
        'minecraft:granite',
        'minecraft:red_sandstone',
        'minecraft:sandstone',
        'minecraft:tuff',
        'minecraft:blackstone',
        'minecraft:calcite',
        'quark:jasper',
        'quark:limestone',
        'quark:soul_sandstone',
        'quark:shale',
        'twilightforest:nagastone',
        'twilightforest:mazestone'
    ]
};
