//priority: 1010

// priority of which mod output should come from, if applicable
const modPriorities = [
    "emendatusenigmatica",
    "minecraft",
    "ftbic",
    "thermal",
    "immersiveengineering",
    "mekanism",
    "kubejs",
    "pneumaticcraft",
    "create",
    "occultism",
    "industrialforegoing",
    "tconstruct",
    "botania",
    "quark",
    "pedestals",
    "refinedstorage",
    "mapperbase",
    "bloodmagic",
    "eidolon",
    "morevanillalib",
    "titanium",
    "mythicbotany",
    "undergarden",
    "byg",
    "atum",
    "betterendforge",
    "miniutilities",
    "chipped",
    "chisel",
    "voluminousenergy",
    "assemblylinemachines",
    "malum"
];

// Used to determine which material types to unify
const typesToUnify = ["nugget", "ingot", "gem", "storage_block", "ore", "dust", "gear", "plate", "rod"];

// Used to determine which materials to unify
const materialsToUnify = [
    "aeternium",
    // "alfsteel",
    "aluminum",
    "andesite",
    "amber",
    "apatite",
    "aquite",
    "bitumen",
    // "blazing",
    "brass",
    "bronze",
    // "certus_quartz",
    "carminite",
    "charcoal",
    // "charged_certus_quartz",
    "charoite",
    "cinnabar",
    // "cloggrum",
    "coal",
    "coal_coke",
    "cobalt",
    // "compressed_iron",
    "constantan",
    "copper",
    "diamond",
    // "dimensional",
    "diopside",
    "electrum",
    "elementium",
    "emerald",
    "enderium",
    // "energized_steel",
    "falsite",
    // "fluix",
    "fluorite",
    // "froststell",
    // "gaia_spirit",
    // "glowstone",
    "gold",
    // "hepatizon",
    "horizonite",
    "iesnium",
    "infused_iron",
    "invar",
    "iron",
    // "knightslime",
    "lapis",
    "lead",
    "lumium",
    // "mana",
    // "manasteel",
    // "manyullyn",
    // "nebu",
    "netherite",
    "nickel",
    // "niotic",
    "niter",
    // "nitro"
    "obsidian",
    "osmium",
    "peridot",
    "platinum",
    "potassium_nitrate",
    "pyrope",
    // "quartz",
    // "queens_slime",
    "redstone",
    // "regalium",
    "refined_glowstone",
    "refined_obsidian",
    "rose_gold",
    "ruby",
    "saltpeter",
    "sapphire",
    "signalum",
    "silver",
    "sky",
    // "slimesteel",
    // "spirited",
    // "starmetal",
    "source",
    "steel",
    "sulfur",
    // "terminite",
    // "terrasteel",
    // "thallasium",
    "tainted_gold",
    "tin",
    // "tinkers_bronze",
    "uranium",
    // "utherium",
    "ventium",
    "wood",
    "zinc",
    "quartz"
];
