//priority: 1001
// priority of which mod output should come from, if applicable
const modPriorities = [
    'emendatusenigmatica',
    'minecraft',
    'ftbic',
    'thermal',
    'immersiveengineering',
    'mekanism',
    'kubejs',
    'pneumaticcraft',
    'create',
    'occultism',
    'industrialforegoing',
    'tconstruct',
    'botania',
    'quark',
    'pedestals',
    'refinedstorage',
    'mapperbase',
    'bloodmagic',
    'eidolon',
    'morevanillalib',
    'titanium',
    'mythicbotany',
    'undergarden',
    'byg',
    'atum',
    'betterendforge',
    'miniutilities',
    'chipped',
    'chisel',
    'voluminousenergy',
    'assemblylinemachines',
    'malum'
];
