
#Gear Config. This config is synced from server to client.
[gear]

	#Meka-Tool Settings
	[gear.mekatool]
		#Base energy (Joules) usage of the Meka-Tool. (Gets multiplied by speed factor)
		energyUsage = "10"
		#Silk touch energy (Joules) usage of the Meka-Tool. (Gets multiplied by speed factor)
		energyUsageSilk = "100"
		#Cost in Joules of using the Meka-Tool to deal 4 units of damage.
		energyUsageWeapon = "2000"
		#Cost in Joules of using the Meka-Tool to teleport 10 blocks.
		energyUsageTeleport = "1000"
		#Maximum distance a player can teleport with the Meka-Tool.
		#Range: 2 ~ 1024
		maxTeleportReach = 100
		#Base bonus damage applied by the Meka-Tool without using any energy.
		#Range: 0 ~ 100000
		baseDamage = 4
		#Efficiency of the Meka-Tool with energy but without any upgrades.
		#Range: 0.1 ~ 100.0
		baseEfficiency = 4.0
		#Energy capacity (Joules) of the Meka-Tool without any installed upgrades. Quadratically scaled by upgrades.
		baseEnergyCapacity = "16000000"
		#Amount (joules) of energy the Meka-Tool can accept per tick. Quadratically scaled by upgrades.
		chargeRate = "100000"
		#Cost in Joules of using the Meka-Tool as a hoe.
		energyUsageHoe = "10"
		#Cost in Joules of using the Meka-Tool as a shovel for making paths and dowsing campfires.
		energyUsageShovel = "10"
		#Cost in Joules of using the Meka-Tool as an axe for stripping logs, scraping, or removing wax.
		energyUsageAxe = "10"
		#Cost in Joules of using the Meka-Tool to shear entities.
		energyUsageShearEntity = "10"
		#Enable the 'Extended Vein Mining' mode for the Meka-Tool. (Allows vein mining everything not just ores/logs)
		extendedMining = true
		#Attack speed of the Meka-Tool.
		#Range: -4.0 ~ 100.0
		attackSpeed = -2.4

	#MekaSuit Settings
	[gear.mekasuit]
		#Energy capacity (Joules) of MekaSuit items without any installed upgrades. Quadratically scaled by upgrades.
		baseEnergyCapacity = "16000000"
		#Amount (joules) of energy the MekaSuit can accept per tick. Quadratically scaled by upgrades.
		chargeRate = "100000"
		#Energy usage (Joules) of MekaSuit when adding 0.1 to jump motion.
		baseJumpEnergyUsage = "1000"
		#Energy usage (Joules) per second of the MekaSuit when flying with the Elytra Unit.
		elytraEnergyUsage = "32000"
		#Energy usage (Joules) of MekaSuit when lessening a potion effect.
		energyUsagePotionTick = "40000"
		#Energy cost/multiplier in Joules for reducing magic damage via the inhalation purification unit. Energy cost is: MagicDamage * energyUsageMagicPrevent. (1 MagicDamage is 1 half heart).
		energyUsageMagicReduce = "1000"
		#Energy cost/multiplier in Joules for reducing fall damage with MekaSuit Boots. Energy cost is: FallDamage * freeRunnerFallEnergyCost. (1 FallDamage is 1 half heart)
		energyUsageFall = "50"
		#Energy usage (Joules) of MekaSuit when adding 0.1 to sprint motion.
		energyUsageSprintBoost = "100"
		#Energy usage (Joules) of MekaSuit per tick when flying via Gravitational Modulation.
		energyUsageGravitationalModulation = "1000"
		#Charge rate of inventory items (Joules) per tick.
		inventoryChargeRate = "10000"
		#Solar recharging rate (Joules) of helmet per tick, per upgrade installed.
		solarRechargingRate = "500"
		#Energy usage (Joules) of MekaSuit per tick of using vision enhancement.
		energyUsageVisionEnhancement = "500"
		#Energy usage (Joules) of MekaSuit per tick of using hydrostatic repulsion.
		energyUsageHydrostaticRepulsion = "500"
		#Energy usage (Joules) of MekaSuit per half-food of nutritional injection.
		energyUsageNutritionalInjection = "20000"
		#Energy usage (Joules) of MekaSuit per unit of damage applied.
		energyUsageDamage = "100000"
		#Energy usage (Joules) of MekaSuit per tick of attracting a single item.
		energyUsageItemAttraction = "250"
		#Maximum amount of Nutritional Paste storable by the nutritional injection unit.
		#Range: > 1
		nutritionalMaxStorage = 128000
		#Rate at which Nutritional Paste can be transferred into the nutritional injection unit.
		#Range: > 1
		nutritionalTransferRate = 256
		#Maximum amount of Hydrogen storable in the jetpack unit.
		#Range: 1 ~ 9223372036854775807
		jetpackMaxStorage = 48000
		#Rate at which Hydrogen can be transferred into the jetpack unit.
		#Range: 1 ~ 9223372036854775807
		jetpackTransferRate = 256
		#Armor value of MekaSuit Helmets.
		#Range: > 0
		helmetArmor = 3
		#Armor value of MekaSuit BodyArmor.
		#Range: > 0
		bodyArmorArmor = 8
		#Armor value of MekaSuit Pants.
		#Range: > 0
		pantsArmor = 6
		#Armor value of MekaSuit Boots.
		#Range: > 0
		bootsArmor = 3
		#Toughness value of the MekaSuit.
		#Range: 0.0 ~ 3.4028234663852886E38
		toughness = 3.0
		#Knockback resistance value of the MekaSuit.
		#Range: 0.0 ~ 3.4028234663852886E38
		knockbackResistance = 0.10000000149011612
		#Should the Gravitational Modulation unit give off vibrations when in use.
		gravitationalVibrations = true

		[gear.mekasuit.damage_absorption]
			#Percent of damage taken from fall that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			fallDamageReductionRatio = 1.0
			#Percent of damage taken from magic damage that can be absorbed by MekaSuit Helmet with Purification unit when it has enough power.
			#Range: 0.0 ~ 1.0
			magicDamageReductionRatio = 1.0
			#Percent of damage taken from other non explicitly supported damage types that don't bypass armor when the MekaSuit has enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			unspecifiedDamageReductionRatio = 1.0
			#Percent of damage taken from anvil that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			anvilDamageReductionRatio = 1.0
			#Percent of damage taken from cactus that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			cactusDamageReductionRatio = 1.0
			#Percent of damage taken from cramming that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			crammingDamageReductionRatio = 1.0
			#Percent of damage taken from dragonBreath that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			dragonBreathDamageReductionRatio = 1.0
			#Percent of damage taken from dryout that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			dryoutDamageReductionRatio = 1.0
			#Percent of damage taken from fallingBlock that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			fallingBlockDamageReductionRatio = 1.0
			#Percent of damage taken from flyIntoWall that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			flyIntoWallDamageReductionRatio = 1.0
			#Percent of damage taken from generic that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			genericDamageReductionRatio = 1.0
			#Percent of damage taken from hotFloor that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			hotFloorDamageReductionRatio = 1.0
			#Percent of damage taken from inFire that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			inFireDamageReductionRatio = 1.0
			#Percent of damage taken from inWall that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			inWallDamageReductionRatio = 1.0
			#Percent of damage taken from lava that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			lavaDamageReductionRatio = 1.0
			#Percent of damage taken from lightningBolt that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			lightningBoltDamageReductionRatio = 1.0
			#Percent of damage taken from onFire that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			onFireDamageReductionRatio = 1.0
			#Percent of damage taken from sweetBerryBush that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			sweetBerryBushDamageReductionRatio = 1.0
			#Percent of damage taken from wither that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			witherDamageReductionRatio = 1.0
			#Percent of damage taken from freeze that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			freezeDamageReductionRatio = 1.0
			#Percent of damage taken from fallingStalactite that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			fallingStalactiteDamageReductionRatio = 1.0
			#Percent of damage taken from stalagmite that can be absorbed by the MekaSuit when there is enough power and a full suit is equipped.
			#Range: 0.0 ~ 1.0
			stalagmiteDamageReductionRatio = 1.0

