ClientEvents.highPriorityAssets((event) => {
    // https://github.com/emilyploszaj/emi/wiki/Hiding-and-Adding-Index-Stacks
    if (global.isExpertMode == false) {
        return;
    }

    const materials = [
        'aeternium',
        'aluminum',
        'amber',
        'andesite',
        'apatite',
        'apple',
        'aquite',
        'bamboo',
        'beetroot',
        'bitumen',
        'brass',
        'bronze',
        'carminite',
        'carrot',
        'charcoal',
        'charoite',
        'cinnabar',
        'coal_coke',
        'coal',
        'cobalt',
        'coke',
        'constantan',
        'copper',
        'deepslate',
        'diamond',
        'dimensional',
        'diopside',
        'electrum',
        'elementium',
        'emerald',
        'ender_pearl',
        'enderium',
        'falsite',
        'flax',
        'fluorite',
        'gold',
        'gunpowder',
        'hop_graphite',
        'hops',
        'horizonite',
        'iesnium',
        'infused_iron',
        'invar',
        'iridium',
        'iron',
        'lapis',
        'lead',
        'lumium',
        'nether_gold',
        'nether_quartz',
        'netherite',
        'nickel',
        'niter',
        'obsidian',
        'onion',
        'osmium',
        'peridot',
        'platinum',
        'potato',
        'pyrope',
        'quartz',
        'raw_zinc',
        'redstone',
        'refined_glowstone',
        'refined_obsidian',
        'rice',
        'rose_gold',
        'ruby',
        'saltpeter',
        'sapphire',
        'signalum',
        'silver',
        'sky',
        'source',
        'steel',
        'sugar_cane',
        'sulfur',
        'tainted_gold',
        'tin',
        'tomato',
        'uranium',
        'ventium',
        'wood',
        'zinc'
    ];
    const thermal = [
        'onion',
        'deepslate',
        'lead',
        'niter',
        'flax',
        'hops',
        'nickel',
        'raw',
        'rice',
        'ruby',
        'sapphire',
        'sawdust',
        'silver',
        'sulfur',
        'tin',
        'tomato',
        'apatite',
        'bitumen',
        'cinnabar'
    ];
    const regex_materials = `(${materials.join('|')})`;
    const regex_thermal = `(${thermal.join('|')})`;
    const payload = {
        filters: [
            `/immersiveengineering:(stick|dust|plate|ingot|nugget|raw|raw_block|storage|ore|deepslate_ore)_${regex_materials}/`,
            `/emendatusenigmatica:(iron|gold|copper|diamond|emerald|netherite|raw|)_(gold|copper|iron|ingot|nugget|block)/`,
            `/emendatusenigmatica:${regex_materials}_air/`,
            `/create:(crushed_raw|andesite_alloy|golden_sheet|raw_zinc|deepslate_ore)/`,
            `/mekanism:(clump|dirty_dust|crystal|shard|sawdust|${regex_materials})/`,
            `/mekanism:(dust|ingot|nugget|raw|block_raw|block)_${regex_materials}/`,
            `/thermal:${regex_materials}_(dust|ingot|nugget|plate|gear|block|seeds)/`,
            `/createaddition:${regex_materials}_(ingot|nugget|sheet|rod)/`,
            `/occultism:${regex_materials}_(dust|ingot|nugget|block|ore)/`,
            `/occultism:ritual_dummy/craft_(miner|dimensional_mineshaft)/`,
            `/create:${regex_materials}_(ingot|nugget|sheet|block|ore)/`,
            `/occultism:(infused|spirit_attuned|butcher|block|raw)/`,
            `/createaddition:${regex_materials}_(wire|grit)/`,
            `/farmersdelight:(beetroot|carrot|potato)_crate/`,
            `/industrialforegoing:(diamond|gold|iron)_gear/`,
            `/powah:(uraninite_ore|deepslate_uraninite)/`,
            `/minecraft:deepslate_${regex_materials}/`,
            `/immersiveengineering:(coke|slag)/`,
            `/minecraft:${regex_materials}_ore/`,
            `/naturesaura:(sky|infused|tainted)/`,
            `/emendatusenigmatica:andesite/`,
            `/thermal:${regex_thermal}/`,
            `sushigocrafting:rice_seeds`,
            `/ars_nouveau:source_gem/`,
            'twilightforest:carminite',
            `quark:charcoal_block`,
            `sushigocrafting:rice`,
            `ae2:ender_dust`,
            `/pendorite/`,
            `/ametrine/`




            // Create, Natures Aura
        ],
        disable: true
    };

    JsonIO.write(`kubejs/assets/emi/index/stacks/emi_unify_materials.json`, payload);
});
