ServerEvents.tags('item', (event) => {
    event
        .get('forge:armors')
        .add([
            /_chestplate/,
            'ars_nouveau:apprentice_robes',
            'ars_nouveau:archmage_robes',
            'ars_nouveau:novice_robes',
            'immersiveengineering:armor_faraday_chest',
            'immersiveengineering:armor_steel_chest',
            'mekanism:hazmat_gown',
            'mekanism:jetpack',
            'mekanism:jetpack_armored',
            'mekanism:mekasuit_bodyarmor',
            'naturesaura:infused_iron_chest',
            'naturesaura:sky_chest'
        ])
        .remove(['pneumaticcraft:jet_boots_upgrade_1']);
    event
        .get('forge:armors/chestplates')
        .add([
            /_chestplate/,
            'ars_nouveau:apprentice_robes',
            'ars_nouveau:archmage_robes',
            'ars_nouveau:novice_robes',
            'immersiveengineering:armor_faraday_chest',
            'immersiveengineering:armor_steel_chest',
            'mekanism:hazmat_gown',
            'mekanism:jetpack',
            'mekanism:jetpack_armored',
            'mekanism:mekasuit_bodyarmor',
            'naturesaura:infused_iron_chest',
            'naturesaura:sky_chest'
        ])
        .remove(['pneumaticcraft:jet_boots_upgrade_1']);
});
