ServerEvents.tags('item', (event) => {
    event
        .get('forge:armors')
        .add([
            /_helmet/,
            'ars_nouveau:apprentice_hood',
            'ars_nouveau:archmage_hood',
            'ars_nouveau:novice_hood',
            'immersiveengineering:armor_faraday_head',
            'immersiveengineering:armor_steel_head',
            'mekanism:hazmat_mask',
            'mekanism:scuba_mask'
        ]);
    event
        .get('forge:armors/helmets')
        .add([
            /_helmet/,
            'ars_nouveau:apprentice_hood',
            'ars_nouveau:archmage_hood',
            'ars_nouveau:novice_hood',
            'immersiveengineering:armor_faraday_head',
            'immersiveengineering:armor_steel_head',
            'mekanism:hazmat_mask',
            'mekanism:scuba_mask'
        ]);
});
