ServerEvents.tags('item', (event) => {
    event
        .get('enigmatica:containers/basic')
        .add([
            /chest$/,
            /sophisticatedstorage:.*barrel/,
            /cabinet/,
            /shulker_box/,
            '#forge:chests',
            'farmersdelight:basket',
            'immersiveengineering:crate',
            'immersiveengineering:reinforced_crate',
            'minecraft:barrel',
            'minecraft:dispenser',
            'minecraft:dropper'
        ])
        .remove([
            'naturesaura:sky_chest',
            'naturesaura:infused_iron_chest',
            'immersiveengineering:armor_steel_chest',
            'immersiveengineering:armor_faraday_chest',
            'functionalstorage:armory_cabinet'
        ]);
});
