ServerEvents.tags('item', (event) => {
    event
        .get('enigmatica:containers/liquid')
        .add([
            /_tank/,
            /fluid_storage/,
            /ae2:fluid_storage_cell_/,
            'immersiveengineering:tank',
            'mekanism:dynamic_valve'
        ])
        .remove([
            'pneumaticcraft:etching_tank',
            'mekanism:scuba_tank',
            'mekanism:basic_chemical_tank',
            'mekanism:advanced_chemical_tank',
            'mekanism:elite_chemical_tank',
            'mekanism:ultimate_chemical_tank',
            'mekanism:creative_chemical_tank'
        ]);
});
