
#Mekanism Common Config. This config is not synced between server and client.
[common]
	#Displayed energy type in Mekanism GUIs and network reader readings.
	#Allowed Values: JOULES, FORGE_ENERGY, ELECTRICAL_UNITS
	energyType = "FORGE_ENERGY"
	#Displayed temperature unit in Mekanism GUIs and network reader readings.
	#Allowed Values: KELVIN, CELSIUS, RANKINE, FAHRENHEIT, AMBIENT
	temperatureUnit = "KELVIN"
	#Show time to decay radiation when readings are above safe levels. Set to false on the client side to disable MekaSuit Geiger and Dosimeter Unit timers. Set to false on the server side to disable handheld Geiger Counter and Dosimeter timers.
	enableDecayTimers = true

