
[consumption]
	#The amount of a resource to use for a given shield type.
	#The amount of botania mana to consume when recharging a single shield HP.
	botania_mana = 400
	#The amount of forge energy (FE) to consume when recharging a single shield HP.
	energy = 3000

[enchantments]
	#Configuration for power of various enchantments in the mod.
	#The damage added to attacks while shields are depleted with the raging enchantment.
	raging_damage_added = 2.0
	#The damage multiplier for attacks of the amplify enchantment.
	amplify_damage_multiplier = 1.5
	#The amount of shield HP drained when the amplify enchantment is triggered.
	amplify_shield_drain = 3
	#The amount of shield HP added for reach level of shield capacity enchantment.
	shield_capacity_increase = 2
	#The multiplier for the recharge rate of the shield applied by the quickened enchantment.
	quicken_multiplier = 0.2
	#The duration of the effect applied by the triggered nova enchantment.
	nova_effect_duration = 5
	#The radius of a nova enchantment's triggered effect.
	nova_range = 1.5
	#The duration of the effect applied when a mob attacks you.
	spike_effect_duration = 2

[shields]


	[shields.metal]

		#Shields made from materials often present in a variety of mods
		[shields.metal.bronze_shield]
			#The amount of health the shield has. One point is half a shield icon (same as hearts.)
			capacity = 7
			#The amount of ticks between each attempt to recharge the shield bar.
			recharge_rate = 40
			#The amount of ticks without taking damage before the shield begins to recharge.
			recharge_delay = 100

		[shields.metal.electrum_shield]
			#The amount of health the shield has. One point is half a shield icon (same as hearts.)
			capacity = 6
			#The amount of ticks between each attempt to recharge the shield bar.
			recharge_rate = 20
			#The amount of ticks without taking damage before the shield begins to recharge.
			recharge_delay = 20

		[shields.metal.constantan_shield]
			#The amount of health the shield has. One point is half a shield icon (same as hearts.)
			capacity = 5
			#The amount of ticks between each attempt to recharge the shield bar.
			recharge_rate = 30
			#The amount of ticks without taking damage before the shield begins to recharge.
			recharge_delay = 60

[ars_nouveau]

	#Shields made from materials present in Ars Nouveau
	[ars_nouveau.enchanter_shield]
		#The amount of health the shield has. One point is half a shield icon (same as hearts.)
		capacity = 14
		#The amount of ticks between each attempt to recharge the shield bar.
		recharge_rate = 10
		#The amount of ticks without taking damage before the shield begins to recharge.
		recharge_delay = 60

[twilight_forest]

	#Shields made from materials present in the Twilight Forest
	[twilight_forest.ironwood_shield]
		#The amount of health the shield has. One point is half a shield icon (same as hearts.)
		capacity = 7
		#The amount of ticks between each attempt to recharge the shield bar.
		recharge_rate = 30
		#The amount of ticks without taking damage before the shield begins to recharge.
		recharge_delay = 40

	[twilight_forest.steeleaf_shield]
		#The amount of health the shield has. One point is half a shield icon (same as hearts.)
		capacity = 5
		#The amount of ticks between each attempt to recharge the shield bar.
		recharge_rate = 20
		#The amount of ticks without taking damage before the shield begins to recharge.
		recharge_delay = 10

	[twilight_forest.knightmetal_shield]
		#The amount of health the shield has. One point is half a shield icon (same as hearts.)
		capacity = 9
		#The amount of ticks between each attempt to recharge the shield bar.
		recharge_rate = 40
		#The amount of ticks without taking damage before the shield begins to recharge.
		recharge_delay = 80