
["YUNG's Better Desert Temples"]

	###########################################################################################################
	## General settings.
	###########################################################################################################
	["YUNG's Better Desert Temples".General]
		# Whether or not vanilla desert pyramids should be disabled.
		# Default: true
		#
		"Disable Vanilla Pyramids" = true
		# Whether or not mining fatigue is applied to players in the desert temple if it has not yet been cleared.
		# Default: true
		#
		"Apply Mining Fatigue" = true

