
["Chimes Config"]
	#Customize the radius needed to repel Phantoms from a chiming Wind Chime. [Default is 25]
	#Range: 0 ~ 35
	"Phantom Repel Radius Vertical" = 25
	#Customize the radius needed to repel Phantoms from a chiming Wind Chime. [Default is 10]
	#Range: 0 ~ 20
	"Phantom Repel Radius Horizontal" = 10

