
["List of Extra Fonts"]
	#list of fonts that can be used, mainly for the book of shadows
	font_list = ["minecraft:default", "hexerei:fancy", "hexerei:bloody", "hexerei:earth", "hexerei:seattle", "hexerei:medieval", "hexerei:augusta"]

