#Draw a black box behind effect icons
effect_box = true
#A list of effects that should not be registered nor shown in JEI
hidden_effects = [""]
#Show effect colors in tooltip
effect_color = true
#Show ingredients list along with an effect description
ingredients_list = true

