
#Client-side Settings
[client]
	#Determines whether JEI and creative tab will show tinted storage items for iron and higher tiers. Can help with easily removing many of these items from there.
	showHigherTierTintedVariants = true

