
["General Configs"]
	#Transfer rate of the energy starbuncles
	#Range: > 1
	starbattery_ratio = 500000
	#Value of milli-bucket of fluid converted in source by the sourcelink
	#Example entry: "minecraft:lava=1.6"
	fluid_to_source = ["industrialforegoing:ether_gas=5.0", "starbunclemania:source_fluid=0.9", "pneumaticcraft:biodiesel=0.5", "immersiveengineering:biodiesel=0.5", "industrialforegoing:sludge=0.1"]
	#Transfer rate of the gas starbuncles
	#Range: > 1
	starballoon_ratio = 16000
	#Threshold rate of the gas starbuncles, lower this if you need them to check and fill more often.
	#Range: > 1
	starballoon_threshold = 250
	#Threshold rate of the energy starbuncles, lower this if you need them to check and fill more often.
	#Range: > 1
	starbattery_threshold = 1000
	#Threshold of the fluid starbuncles, lower this if you need them to check and fill more often.
	#Range: > 1
	starbucket_threshold = 250
	#Transfer rate of the fluid starbuncles
	#Range: > 1
	starbucket_ratio = 16000
	#Source cost to make a bucket of liquid source.
	#Range: > 1
	source_condense_cost = 1000

["Mekanism Compat"]
	#How much energy is produced per mB of Gaseous Source
	#Range: 0 ~ 9223372036854775807
	source_gas_energy_density = 200

