ServerEvents.genericLootTables((event) => {
    event.addGeneric(`twilightforest:structures/useless`, (table) => {
        table.addPool((pool) => {
            pool.rolls = 1.0;
            pool.addItem('minecraft:feather', 1, [1, 3]);
            pool.addItem('minecraft:wheat_seeds', 1, [1, 2]);
            pool.addItem('minecraft:flint', 1, [1, 2]);
            pool.addItem('minecraft:cactus', 1, [1, 2]);
            pool.addItem('minecraft:sugar_cane', 1, [1, 4]);
            pool.addItem('minecraft:flower_pot', 1, 1);
            pool.addItem('thermal:phytogro', 1, [1, 4]);
        });

        table.addPool((pool) => {
            pool.rolls = 1.0;
            pool.addItem('minecraft:dandelion', 1, [1, 4]);
            pool.addItem('minecraft:poppy', 1, [1, 4]);
            pool.addItem('minecraft:blue_orchid', 1, [1, 4]);
            pool.addItem('minecraft:allium', 1, [1, 4]);
            pool.addItem('minecraft:azure_bluet', 1, [1, 4]);
            pool.addItem('minecraft:red_tulip', 1, [1, 4]);
            pool.addItem('minecraft:orange_tulip', 1, [1, 4]);
            pool.addItem('minecraft:white_tulip', 1, [1, 4]);
            pool.addItem('minecraft:pink_tulip', 1, [1, 4]);
            pool.addItem('minecraft:oxeye_daisy', 1, [1, 4]);
            pool.addItem('minecraft:cornflower', 1, [1, 4]);
            pool.addItem('minecraft:lily_of_the_valley', 1, [1, 4]);
            pool.addItem('byg:allium_flower_bush', 1, [1, 4]);
            pool.addItem('byg:alpine_bellflower', 1, [1, 4]);
            pool.addItem('byg:amaranth', 1, [1, 4]);
            pool.addItem('byg:angelica', 1, [1, 4]);
            pool.addItem('byg:hydrangea_bush', 1, [1, 4]);
            pool.addItem('byg:begonia', 1, [1, 4]);
            pool.addItem('byg:bistort', 1, [1, 4]);
            pool.addItem('byg:blue_sage', 1, [1, 4]);
            pool.addItem('byg:black_rose', 1, [1, 4]);
            pool.addItem('byg:california_poppy', 1, [1, 4]);
            pool.addItem('byg:crocus', 1, [1, 4]);
            pool.addItem('byg:cyan_amaranth', 1, [1, 4]);
            pool.addItem('byg:cyan_rose', 1, [1, 4]);
            pool.addItem('byg:cyan_tulip', 1, [1, 4]);
            pool.addItem('byg:daffodil', 1, [1, 4]);
            pool.addItem('byg:fairy_slipper', 1, [1, 4]);
            pool.addItem('byg:firecracker_flower_bush', 1, [1, 4]);
            pool.addItem('byg:foxglove', 1, [1, 4]);
            pool.addItem('byg:golden_spined_cactus', 1, [1, 4]);
            pool.addItem('byg:green_tulip', 1, [1, 4]);
            pool.addItem('byg:guzmania', 1, [1, 4]);
            pool.addItem('byg:incan_lily', 1, [1, 4]);
            pool.addItem('byg:iris', 1, [1, 4]);
            pool.addItem('byg:japanese_orchid', 1, [1, 4]);
            pool.addItem('byg:kovan_flower', 1, [1, 4]);
            pool.addItem('byg:lazarus_bellflower', 1, [1, 4]);
            pool.addItem('byg:lollipop_flower', 1, [1, 4]);
            pool.addItem('byg:magenta_amaranth', 1, [1, 4]);
            pool.addItem('byg:magenta_tulip', 1, [1, 4]);
            pool.addItem('byg:orange_amaranth', 1, [1, 4]);
            pool.addItem('byg:orange_daisy', 1, [1, 4]);
            pool.addItem('byg:osiria_rose', 1, [1, 4]);
            pool.addItem('byg:peach_leather_flower', 1, [1, 4]);
            pool.addItem('byg:pink_allium', 1, [1, 4]);
            pool.addItem('byg:pink_allium_flower_bush', 1, [1, 4]);
            pool.addItem('byg:pink_anemone', 1, [1, 4]);
            pool.addItem('byg:pink_daffodil', 1, [1, 4]);
            pool.addItem('byg:protea_flower', 1, [1, 4]);
            pool.addItem('byg:purple_amaranth', 1, [1, 4]);
            pool.addItem('byg:purple_sage', 1, [1, 4]);
            pool.addItem('byg:purple_tulip', 1, [1, 4]);
            pool.addItem('byg:richea', 1, [1, 4]);
            pool.addItem('byg:rose', 1, [1, 4]);
            pool.addItem('byg:snowdrops', 1, [1, 4]);
            pool.addItem('byg:silver_vase_flower', 1, [1, 4]);
            pool.addItem('byg:torch_ginger', 1, [1, 4]);
            pool.addItem('byg:violet_leather_flower', 1, [1, 4]);
            pool.addItem('byg:white_anemone', 1, [1, 4]);
            pool.addItem('byg:white_sage', 1, [1, 4]);
            pool.addItem('byg:winter_rose', 1, [1, 4]);
            pool.addItem('byg:winter_cyclamen', 1, [1, 4]);
            pool.addItem('byg:winter_scilla', 1, [1, 4]);
            pool.addItem('byg:yellow_daffodil', 1, [1, 4]);
            pool.addItem('byg:yellow_tulip', 1, [1, 4]);
        });
    });
});
