ServerEvents.tags('item', (event) => {
    event
        .get('forge:tools')
        .add([
            /_paxel/,
            /_aiot/,
            'immersiveengineering:buzzsaw',
            'immersiveengineering:drill',
            'industrialforegoing:infinity_drill',
            'industrialforegoing:infinity_saw',
            'mekanism:atomic_disassembler',
            'mekanism:meka_tool',
            'mininggadgets:mininggadget',
            'pneumaticcraft:jackhammer',
            'thermal:flux_drill',
            'thermal:flux_saw'
        ]);
    event
        .get('forge:tools/multi_tools')
        .add([
            /_paxel/,
            /_aiot/,
            'immersiveengineering:buzzsaw',
            'immersiveengineering:drill',
            'industrialforegoing:infinity_drill',
            'industrialforegoing:infinity_saw',
            'mekanism:atomic_disassembler',
            'mekanism:meka_tool',
            'mininggadgets:mininggadget',
            'pneumaticcraft:jackhammer',
            'thermal:flux_drill',
            'thermal:flux_saw'
        ]);
    event
        .get('forge:multi_tools')
        .add([
            /_paxel/,
            /_aiot/,
            'immersiveengineering:buzzsaw',
            'immersiveengineering:drill',
            'industrialforegoing:infinity_drill',
            'industrialforegoing:infinity_saw',
            'mekanism:atomic_disassembler',
            'mekanism:meka_tool',
            'mininggadgets:mininggadget',
            'pneumaticcraft:jackhammer',
            'thermal:flux_drill',
            'thermal:flux_saw'
        ]);
});
